### ISSUE TITLE
A question about keysuffixes

### ISSUE THREAD

**Issue by yangbodong22011** [rmind/masstree#2]
Hi:
Thanks for your masstree, it's cool.
I have a question about keysuffixes, my code is as follows:
```
tree = masstree_create(NULL);
char* key = "01234567AB";
char* key2 = "01234567XY";
masstree_put(tree, key, sizeof(key), (void *)1);
masstree_put(tree, key2, sizeof(key2), (void *)2);
```

I debug this and find key suffixes stored in layer 1, just like :

```
Layer 0              keyslice[0]: 01234567
                                 |
                               /  
Layer 1             keyslice[0]:AB         
                    keyslice[1]:XY
```
Layer 1 is leaf nodes in B+ tree, so, I think keyslice should store a complete key for range, and in paper, it has keysuffix_t keysuffixes, but I did not find in your code. 

So, why store keysuffixes in keys-lice?

**Comment by rmind** [comment]
Hi,

This is not a reference implementation, but a variation of Masstree. So, not all features and optimisations described in the original paper are implemented. I might add it in the future.

Also, please note that this is experimental and unstable code (in particular, delete operation is known to have bugs/races in multi-threaded environment). I updated the project information to reflect more clearly that this code is experimental and the support is currently not provided.

Thanks.

**Comment by UncP** [comment]
@yangbodong22011, you can take a look at my implementation if you are interested, it takes a different approach, layers are created lazily. https://github.com/UncP/aili
